logging:
  version: 1
  formatters:
    simple:
      format: '%(name)s - %(funcName)s - %(levelname)s - %(message)s'
    verbose:
      format: '%(asctime)s - %(name)s - %(funcName)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
  root:
    handlers: [console]
services:
  turnout:
    update-rate: 0.04
    angular-speed: 20
    turnouts:
      - name: A
        angles:
          main: 0
          diverging: 180
        outputs:
          - name: servo
            type: PCA9685
            address: 0x40
            pin: 0
          - name: frog
            type: PCA9685
            address: 0x40
            pin: 4
      - name: B
        angles:
          main: 45
          diverging: 135
        outputs:
          - name: servo
            type: PCA9685
            address: 0x40
            pin: 1
          - name: frog
            type: PCA9685
            address: 0x40
            pin: 5