logging:
  version: 1
  formatters:
    simple:
      format: '%(name)s - %(funcName)s - %(levelname)s - %(message)s'
    verbose:
      format: '%(asctime)s - %(name)s - %(funcName)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: verbose
      filename: 'details.log'
      mode: 'w'
      encoding: 'utf-8'
  root:
    level: DEBUG
    handlers: [console]
services:
  turnout:
    update-rate: 1
    angular-speed: 5
    turnouts:
      - name: A
        angles:
          main: 45
          diverging: 135
        outputs:
          - name: servo
            type: PCA9685
            address: 0x40
            pin: 0
          - name: frog
            type: PCA9685
            address: 0x40
            pin: 4
      - name: B
        angles:
          main: 45
          diverging: 135
        outputs:
          - name: servo
            type: PCA9685
            address: 0x40
            pin: 1
          - name: frog
            type: PCA9685
            address: 0x40
            pin: 5